import sys, os
ROOT_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
if ROOT_DIR not in sys.path: sys.path.append(ROOT_DIR)
for folder in ['models', 'utils', 'recording', 'ingestion', 'models/K Prophet', 'models/HR']:
    path = os.path.join(ROOT_DIR, folder)
    if path not in sys.path: sys.path.append(path)

ROOT_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
if ROOT_DIR not in sys.path: sys.path.append(ROOT_DIR)
for folder in ['models', 'utils', 'recording', 'ingestion', 'models/K Prophet', 'models/HR']:
    path = os.path.join(ROOT_DIR, folder)
    if path not in sys.path: sys.path.append(path)
#!/usr/bin/env python3
import json
import os
import urllib.request
from datetime import datetime

def fetch_json(url):
    with urllib.request.urlopen(url) as response:
        return json.loads(response.read().decode())

def fetch_lineups(date_str=None):
    if not date_str:
        date_str = datetime.now().strftime("%Y-%m-%d")
        
    print(f"🔄 Syncing Lineups for {date_str} via MLB Stats API...")
    
    schedule_url = f"https://statsapi.mlb.com/api/v1/schedule?sportId=1&date={date_str}"
    try:
        schedule = fetch_json(schedule_url)
    except Exception as e:
        print(f"❌ Error fetching schedule: {e}")
        return

    dates = schedule.get('dates', [])
    if not dates:
        print("⚠️ No games found for this date.")
        return
        
    games = dates[0].get('games', [])
    confirmed_games = []
    
    for game in games:
        game_pk = game['gamePk']
        away_team = game['teams']['away']['team']['name']
        home_team = game['teams']['home']['team']['name']
        
        boxscore_url = f"https://statsapi.mlb.com/api/v1/game/{game_pk}/boxscore"
        try:
            box_resp = fetch_json(boxscore_url)
            
            def get_players(team_key):
                order = box_resp['teams'][team_key]['battingOrder']
                players = box_resp['teams'][team_key]['players']
                lineup = []
                for p_id in order:
                    p_data = players.get(f"ID{p_id}", {})
                    name = p_data.get('person', {}).get('fullName', 'Unknown')
                    hand = p_data.get('person', {}).get('batSide', {}).get('code', 'R')
                    lineup.append([name, hand])
                return lineup

            away_lineup = get_players('away')
            home_lineup = get_players('home')
            
            # Simple check for pitcher
            away_p = "TBD"
            home_p = "TBD"
            
            confirmed_games.append({
                'away': {'team': away_team, 'pitcher': away_p, 'lineup': away_lineup},
                'home': {'team': home_team, 'pitcher': home_p, 'lineup': home_lineup}
            })
            print(f"  ✅ Parsed {away_team} @ {home_team}")
            
        except Exception as e:
            print(f"  ⚠️ Skipping {away_team} @ {home_team}: (Not started or API error)")

    if confirmed_games:
        with open('games_data.py', 'w') as f:
            f.write("# Auto-generated by sync_lineups.py\n")
            f.write("GAMES = " + json.dumps(confirmed_games, indent=4))
        print(f"🚀 games_data.py updated with {len(confirmed_games)} confirmed matchups.")

if __name__ == "__main__":
    fetch_lineups()